### ISSUE TITLE
shiny app in a package  

### ISSUE THREAD

**Issue by lgatto** [statOmics/msqrob2gui#2]
I recommend to look at the [shinyAppDemo](https://github.com/mangothecat/shinyAppDemo) example package/app. It as all the code in the R directory, which will this get checked by `R CMD check`. It also invites to better code structuring and this testable functions.

**Comment by statOmics** [comment]
Laurent, I used that package to design the msqrob2gui. I have exactly the same structure. I only added a utilities.R file with functions for plotting.
The UI and server are just having much more functionalities. Perhaps we might discuss how to structure these...
